# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.utils.wfs_utils.scheduler_controller_pb2 as scheduler__controller__pb2


class SchedulerControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.KeepAlive = channel.unary_unary(
                '/scheduler_controller.SchedulerController/KeepAlive',
                request_serializer=scheduler__controller__pb2.KeepAliveRequest.SerializeToString,
                response_deserializer=scheduler__controller__pb2.KeepAliveReply.FromString,
                )
        self.InputWorkflow = channel.unary_unary(
                '/scheduler_controller.SchedulerController/InputWorkflow',
                request_serializer=scheduler__controller__pb2.InputWorkflowRequest.SerializeToString,
                response_deserializer=scheduler__controller__pb2.InputWorkflowReply.FromString,
                )


class SchedulerControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def KeepAlive(self, request, context):
        """调度器内保活器向调度器控制器发送保活信号
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InputWorkflow(self, request, context):
        """前端输入工作流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'KeepAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.KeepAlive,
                    request_deserializer=scheduler__controller__pb2.KeepAliveRequest.FromString,
                    response_serializer=scheduler__controller__pb2.KeepAliveReply.SerializeToString,
            ),
            'InputWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.InputWorkflow,
                    request_deserializer=scheduler__controller__pb2.InputWorkflowRequest.FromString,
                    response_serializer=scheduler__controller__pb2.InputWorkflowReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler_controller.SchedulerController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchedulerController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def KeepAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scheduler_controller.SchedulerController/KeepAlive',
            scheduler__controller__pb2.KeepAliveRequest.SerializeToString,
            scheduler__controller__pb2.KeepAliveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InputWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scheduler_controller.SchedulerController/InputWorkflow',
            scheduler__controller__pb2.InputWorkflowRequest.SerializeToString,
            scheduler__controller__pb2.InputWorkflowReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
