# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler_controller.proto',
  package='scheduler_controller',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ascheduler_controller.proto\x12\x14scheduler_controller\"h\n\x10KeepAliveRequest\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x10\n\x08pressure\x18\x02 \x01(\x07\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x07\x12\x15\n\rserial_number\x18\x04 \x01(\x04\x12\x0c\n\x04ipv4\x18\x05 \x01(\t\"#\n\x0eKeepAliveReply\x12\x11\n\twait_secs\x18\x01 \x01(\x05\"(\n\x14InputWorkflowRequest\x12\x10\n\x08workflow\x18\x01 \x03(\x0c\"$\n\x12InputWorkflowReply\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x01 \x01(\r2\xd7\x01\n\x13SchedulerController\x12Y\n\tKeepAlive\x12&.scheduler_controller.KeepAliveRequest\x1a$.scheduler_controller.KeepAliveReply\x12\x65\n\rInputWorkflow\x12*.scheduler_controller.InputWorkflowRequest\x1a(.scheduler_controller.InputWorkflowReplyb\x06proto3'
)




_KEEPALIVEREQUEST = _descriptor.Descriptor(
  name='KeepAliveRequest',
  full_name='scheduler_controller.KeepAliveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid', full_name='scheduler_controller.KeepAliveRequest.sid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='scheduler_controller.KeepAliveRequest.pressure', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='scheduler_controller.KeepAliveRequest.capacity', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='scheduler_controller.KeepAliveRequest.serial_number', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ipv4', full_name='scheduler_controller.KeepAliveRequest.ipv4', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=156,
)


_KEEPALIVEREPLY = _descriptor.Descriptor(
  name='KeepAliveReply',
  full_name='scheduler_controller.KeepAliveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wait_secs', full_name='scheduler_controller.KeepAliveReply.wait_secs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=193,
)


_INPUTWORKFLOWREQUEST = _descriptor.Descriptor(
  name='InputWorkflowRequest',
  full_name='scheduler_controller.InputWorkflowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow', full_name='scheduler_controller.InputWorkflowRequest.workflow', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=235,
)


_INPUTWORKFLOWREPLY = _descriptor.Descriptor(
  name='InputWorkflowReply',
  full_name='scheduler_controller.InputWorkflowReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accept', full_name='scheduler_controller.InputWorkflowReply.accept', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=273,
)

DESCRIPTOR.message_types_by_name['KeepAliveRequest'] = _KEEPALIVEREQUEST
DESCRIPTOR.message_types_by_name['KeepAliveReply'] = _KEEPALIVEREPLY
DESCRIPTOR.message_types_by_name['InputWorkflowRequest'] = _INPUTWORKFLOWREQUEST
DESCRIPTOR.message_types_by_name['InputWorkflowReply'] = _INPUTWORKFLOWREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeepAliveRequest = _reflection.GeneratedProtocolMessageType('KeepAliveRequest', (_message.Message,), {
  'DESCRIPTOR' : _KEEPALIVEREQUEST,
  '__module__' : 'scheduler_controller_pb2'
  # @@protoc_insertion_point(class_scope:scheduler_controller.KeepAliveRequest)
  })
_sym_db.RegisterMessage(KeepAliveRequest)

KeepAliveReply = _reflection.GeneratedProtocolMessageType('KeepAliveReply', (_message.Message,), {
  'DESCRIPTOR' : _KEEPALIVEREPLY,
  '__module__' : 'scheduler_controller_pb2'
  # @@protoc_insertion_point(class_scope:scheduler_controller.KeepAliveReply)
  })
_sym_db.RegisterMessage(KeepAliveReply)

InputWorkflowRequest = _reflection.GeneratedProtocolMessageType('InputWorkflowRequest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTWORKFLOWREQUEST,
  '__module__' : 'scheduler_controller_pb2'
  # @@protoc_insertion_point(class_scope:scheduler_controller.InputWorkflowRequest)
  })
_sym_db.RegisterMessage(InputWorkflowRequest)

InputWorkflowReply = _reflection.GeneratedProtocolMessageType('InputWorkflowReply', (_message.Message,), {
  'DESCRIPTOR' : _INPUTWORKFLOWREPLY,
  '__module__' : 'scheduler_controller_pb2'
  # @@protoc_insertion_point(class_scope:scheduler_controller.InputWorkflowReply)
  })
_sym_db.RegisterMessage(InputWorkflowReply)



_SCHEDULERCONTROLLER = _descriptor.ServiceDescriptor(
  name='SchedulerController',
  full_name='scheduler_controller.SchedulerController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=276,
  serialized_end=491,
  methods=[
  _descriptor.MethodDescriptor(
    name='KeepAlive',
    full_name='scheduler_controller.SchedulerController.KeepAlive',
    index=0,
    containing_service=None,
    input_type=_KEEPALIVEREQUEST,
    output_type=_KEEPALIVEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InputWorkflow',
    full_name='scheduler_controller.SchedulerController.InputWorkflow',
    index=1,
    containing_service=None,
    input_type=_INPUTWORKFLOWREQUEST,
    output_type=_INPUTWORKFLOWREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULERCONTROLLER)

DESCRIPTOR.services_by_name['SchedulerController'] = _SCHEDULERCONTROLLER

# @@protoc_insertion_point(module_scope)
