apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels: 
    keel.sh/policy: force
    keel.sh/trigger: webhooks
    keel.sh/approvals: "0"
    keel.sh/match-tag: "true"
spec:
  selector:
    matchLabels:
      app: backend-ins
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-ins
    spec:
      containers:
        - name: backend-ins
          imagePullPolicy: Always 
          image: harbor.cloudcontrolsystems.cn/workflow/backend:latest # TODO: change to the real repo address
          env:
            - name: REDIS_HOST
              value: 192.168.1.24:7134
            - name: MONGODB
              value: mongodb-1610110440
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30180
      name: backend-port
  selector:
    app: backend-ins
